name: RSS Importer
description: Import RSS feeds and output standardized artifacts

inputs:
  feeds:
    description: 'List of RSS feed URLs or file paths (one per line)'
    required: true
  output_folder:
    description: 'Output folder for RSS artifacts'
    required: false
    default: 'rss_artifacts'

outputs:
  output_folder:
    description: 'Output folder containing RSS artifacts'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install feedparser requests python-dateutil
      shell: bash

    - name: Create output directory
      run: |
        mkdir -p ${{ inputs.output_folder }}
      shell: bash

    - name: Import RSS feeds
      env:
        FEEDS_INPUT: ${{ inputs.feeds }}
        OUTPUT_FOLDER: ${{ inputs.output_folder }}
      run: |
        python rss_importer.py
      shell: bash

    - name: Set output
      run: |
        echo "output_folder=${{ inputs.output_folder }}" >> $GITHUB_OUTPUT
      shell: bash 