name: Item Counter
description: Count RSS items and output count to file

inputs:
  input_folder:
    description: 'Input folder containing RSS artifacts'
    required: false
    default: 'filtered_rss_artifacts'
  output_folder:
    description: 'Output folder for count artifacts'
    required: false
    default: 'count_artifacts'

outputs:
  output_folder:
    description: 'Output folder containing count artifacts'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create output directory
      run: |
        mkdir -p ${{ inputs.output_folder }}
      shell: bash

    - name: Count RSS items
      env:
        INPUT_FOLDER: ${{ inputs.input_folder }}
        OUTPUT_FOLDER: ${{ inputs.output_folder }}
      run: |
        python item_counter.py
      shell: bash

    - name: Set output
      run: |
        echo "output_folder=${{ inputs.output_folder }}" >> $GITHUB_OUTPUT
      shell: bash 