name: Date Filter
description: Filter RSS items by publication date

inputs:
  input_folder:
    description: 'Input folder containing RSS artifacts'
    required: false
    default: 'rss_artifacts'
  output_folder:
    description: 'Output folder for filtered RSS artifacts'
    required: false
    default: 'filtered_rss_artifacts'
  op:
    description: 'Date comparison operator (GTE, LTE, EQ, GT, LT)'
    required: true
  date_filter:
    description: 'Date to filter by (YYYY-MM-DD format)'
    required: true

outputs:
  output_folder:
    description: 'Output folder containing filtered RSS artifacts'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install python-dateutil
      shell: bash

    - name: Create output directory
      run: |
        mkdir -p ${{ inputs.output_folder }}
      shell: bash

    - name: Filter RSS items by date
      env:
        INPUT_FOLDER: ${{ inputs.input_folder }}
        OUTPUT_FOLDER: ${{ inputs.output_folder }}
        OP: ${{ inputs.op }}
        DATE_FILTER: ${{ inputs.date_filter }}
      run: |
        python actions/transformers/date_filter.py
      shell: bash

    - name: Set output
      run: |
        echo "output_folder=${{ inputs.output_folder }}" >> $GITHUB_OUTPUT
      shell: bash 